version: "3.7"
services:
    # imagem micro 01
    micro_email:
        build: 
            args: 
                user: luanramos
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis_micro_email
            - queue_micro_email
        networks: 
            - microemail
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 8005:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - microemail

    # queue micro 01
    queue_micro_email:
        build: 
            args: 
                user: luanramos
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        networks: 
            - microemail

    #redis
    redis_micro_email:
        image: redis:latest
        networks: 
            - microemail

networks: 
    microemail:
        driver: bridge